services:
  uploader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:80
    volumes:
      - ./uploads:/app/uploads
    networks:
      - deepwater_web

networks:
  deepwater_web:
    external: true