services:
  uploader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:80
    volumes:
      - uploaded_files:/app/uploads
    networks:
      - deepwater_web
volumes:
  uploaded_files:

networks:
  deepwater_web:
    external: true